// This file has been generated by Specta. DO NOT EDIT.

import { createTauRPCProxy as createProxy, type InferCommandOutput } from 'taurpc'
type TAURI_CHANNEL<T> = (response: T) => void


/**
 * Node health snapshot for the TuffSwarm P2P status card.
 */
export type P2pStatus = { enabled: boolean; healthy: boolean; authorized: boolean; control_url: string; token_present: boolean; 
/**
 * True when this status came from the offline/limited fallback path.
 */
degraded: boolean }

const ARGS_MAP = { '':'{"get_p2p_status":[]}' }
export type Router = { "": {get_p2p_status: () => Promise<P2pStatus>} };


export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput }
