<script lang="ts">
  import { Check, Download, RefreshCw, Trash2 } from "@lucide/svelte";
  import type { ModItem } from "./contentModels";
  let { item, selected = false, onToggle, onInstall, onRemove }: { item: ModItem; selected?: boolean; onToggle: () => void; onInstall: () => void; onRemove?: () => void } = $props();
</script>

<article class="group relative flex min-h-[230px] flex-col rounded-2xl border border-white/[0.08] bg-white/[0.035] p-4 transition-all hover:-translate-y-0.5 hover:border-white/20 hover:bg-white/[0.06]">
  <label class="absolute right-3 top-3 z-10 cursor-pointer"><input type="checkbox" checked={selected} onchange={onToggle} aria-label={`Select ${item.name}`} /></label>
  <div class="mb-3 flex items-start gap-3"><div class="h-14 w-14 shrink-0 overflow-hidden rounded-xl border border-white/10 bg-black/30">{#if item.iconUrl}<img src={item.iconUrl} alt="" class="h-full w-full object-cover" loading="lazy" />{:else}<div class="flex h-full items-center justify-center text-lg text-emerald-300">{item.name.slice(0, 1)}</div>{/if}</div><div class="min-w-0 pr-6"><h3 class="truncate text-sm font-semibold text-neutral-100">{item.name}</h3><p class="mt-0.5 truncate text-xs text-[var(--text-secondary)]">by {item.author || "Unknown author"}</p></div></div>
  <p class="line-clamp-2 min-h-9 text-xs leading-5 text-[var(--text-secondary)]">{item.description || "No description available."}</p>
  <div class="mt-auto flex items-center justify-between gap-2 pt-4"><div class="flex items-center gap-2 text-[12px] text-[var(--text-secondary)]"><span class="rounded border border-white/10 px-1.5 py-1 uppercase">{item.provider}</span>{#if item.downloads}<span><Download size={11} class="inline"/> {item.downloads.toLocaleString()}</span>{/if}</div>{#if item.installed}<div class="flex items-center gap-2"><span class="inline-flex items-center gap-2 rounded-lg bg-emerald-500/10 px-2 py-1.5 text-xs font-medium text-emerald-300"><Check size={13}/> Installed</span>{#if onRemove}<button type="button" class="rounded-lg p-1.5 text-[var(--text-secondary)] opacity-0 transition group-hover:opacity-100 hover:bg-red-500/10 hover:text-red-300" onclick={onRemove} title="Remove"><Trash2 size={14}/></button>{/if}</div>{:else if item.updateAvailable}<button type="button" class="inline-flex items-center gap-2 rounded-lg bg-amber-500/15 px-3 py-2 text-xs font-semibold text-amber-200 hover:bg-amber-500/25" onclick={onInstall}><RefreshCw size={13}/> Update</button>{:else}<button type="button" class="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-semibold text-white shadow-[0_0_14px_rgba(16,185,129,.18)] hover:bg-emerald-500" onclick={onInstall}>Install</button>{/if}</div>
</article>
