<script lang="ts">
  import { Github, Globe2, Save, UploadCloud, ChevronDown } from "@lucide/svelte";
  import GithubPackTransport from "./GithubPackTransport.svelte";
  type Config = { githubRepository: string; modrinthProjectId: string; curseforgeProjectId: string; curseforgeGameVersionIds: number[] };
  let { config = $bindable(), gameVersionIdsText = $bindable(""), configSaving = false, configLoading = false, onSave }: { config: Config; gameVersionIdsText?: string; configSaving?: boolean; configLoading?: boolean; onSave: () => void } = $props();
  let open = $state({ github: true, modrinth: true, curseforge: false });
</script>

<section class="grid gap-3 rounded-2xl border border-white/[0.08] bg-neutral-950/40 p-4 backdrop-blur-2xl">
  <div class="flex items-center justify-between"><div><h2 class="m-0 text-sm font-semibold text-neutral-100">Publish config</h2><p class="mt-1 text-xs text-[var(--text-secondary)]">Configure destinations once, then publish from the action bar.</p></div><button type="button" class="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-semibold text-white hover:bg-emerald-500" onclick={onSave} disabled={configSaving || configLoading}><Save size={13}/> {configSaving ? 'Saving…' : 'Save config'}</button></div>
  <details open={open.github} class="rounded-xl border border-white/10 bg-white/[0.03] p-3"><summary class="flex cursor-pointer list-none items-center gap-2 text-sm font-semibold text-neutral-100"><Github size={17} class="text-neutral-200"/> GitHub Releases <span class="ml-auto text-xs text-[var(--text-secondary)]">{config.githubRepository ? 'configured' : 'needs repository'}</span></summary><div class="mt-3 grid gap-3"><label class="text-xs text-[var(--text-secondary)]">Repository<input class="mt-1 w-full bg-black/30 text-sm" bind:value={config.githubRepository} placeholder="owner/repository" /></label><GithubPackTransport bind:repository={config.githubRepository} /><div class="flex gap-4 text-xs text-[var(--text-secondary)]"><label class="flex items-center gap-2"><input type="checkbox"/> Draft</label><label class="flex items-center gap-2"><input type="checkbox"/> Pre-release</label></div></div></details>
  <details open={open.modrinth} class="rounded-xl border border-white/10 bg-white/[0.03] p-3"><summary class="flex cursor-pointer list-none items-center gap-2 text-sm font-semibold text-neutral-100"><Globe2 size={17} class="text-emerald-300"/> Modrinth <span class="ml-auto text-xs text-emerald-300">Token from Settings</span></summary><div class="mt-3 grid gap-3"><label class="text-xs text-[var(--text-secondary)]">Project slug / ID<input class="mt-1 w-full bg-black/30 text-sm" bind:value={config.modrinthProjectId} placeholder="project-slug" /></label><div class="flex gap-2 text-xs text-[var(--text-secondary)]"><span class="rounded-lg border border-emerald-500/30 bg-emerald-500/10 px-2 py-1">Release</span><span class="rounded-lg border border-white/10 px-2 py-1">Beta</span><span class="rounded-lg border border-white/10 px-2 py-1">Alpha</span></div></div></details>
  <details open={open.curseforge} class="rounded-xl border border-white/10 bg-white/[0.03] p-3"><summary class="flex cursor-pointer list-none items-center gap-2 text-sm font-semibold text-neutral-100"><UploadCloud size={17} class="text-orange-300"/> CurseForge <span class="ml-auto text-xs text-[var(--text-secondary)]">{config.curseforgeProjectId ? 'configured' : 'optional'}</span></summary><div class="mt-3 grid gap-3"><label class="text-xs text-[var(--text-secondary)]">Project ID<input class="mt-1 w-full bg-black/30 text-sm" bind:value={config.curseforgeProjectId} placeholder="123456" /></label><label class="text-xs text-[var(--text-secondary)]">Game Version IDs<input class="mt-1 w-full bg-black/30 font-mono text-sm" bind:value={gameVersionIdsText} placeholder="9008, 9990" /></label><label class="text-xs text-[var(--text-secondary)]">Release type<select class="mt-1 w-full bg-black/30 text-sm"><option>Release</option><option>Beta</option><option>Alpha</option></select></label></div></details>
</section>
